### ISSUE TITLE
Variable length input sequence and output sequence

### ISSUE THREAD

**Issue by slashstar** [farizrahman4u/seq2seq#103]
Hi,
I am trying to train a many-to-many(encode-decoder) type LSTM. My input and output sequences, both are of variable length, which requires me to do input and output zero padding. For output I am using sample_weights for masking, how can I do masking for input? For both Seq2seq and AttentionSeq2seq, we need to give input_len.

**Comment by nicoayroles** [comment]
Hi all,

Following https://keras.io/layers/core/#masking, I suggest to modify the following lines in SimpleSeq2Seq (lines 66 to 68):
`	for _ in range(1, depth[0]):
		encoder.add(Dropout(dropout))
		encoder.add(LSTMCell(hidden_dim, **kwargs))`
into
`	for _ in range(1, depth[0]):
		encoder.add(Dropout(dropout))
               encoder.add(Masking(mask_value=mask_value, input_shape=(shape[1], shape[2])))
		encoder.add(LSTMCell(hidden_dim, **kwargs))`
where mask_value in a new SimpleSeq2Seq parameter.
What do you think? I you agree, I can open a pull request on this.

**Comment by farizrahman4u** [comment]
@nicoayroles That wouldn't work.. A cell works timestep wise. Its better to do : Embedding layer with mask zero = True -> Seq2seq model.

**Comment by sri3705** [comment]
@farizrahman4u I tried to use your suggestion and wrote this simple code:

model = Sequential()
model.add(Embedding(args.vocab_size, args.vocab_size, mask_zero=True))
model.add(seq2seq.SimpleSeq2Seq(input_dim=args.vocab_size, hidden_dim=args.rnn_size, output_length=args.seq_length, output_dim=args.vocab_size))
model.compile(loss='mse', optimizer='rmsprop')

It gave me an error:
 File "train.py", line 107, in <module>
    main()
  File "train.py", line 44, in main
    train(args)
  File "train.py", line 78, in train
    model = Model(args)
  File "/mnt/ssd6/srikanth/keybridge_analysis/apps/seq_to_seq_feature/code/model.py", line 15, in __init__
    model.add(seq2seq.SimpleSeq2Seq(input_dim=args.vocab_size, hidden_dim=args.rnn_size, output_length=args.seq_length, output_dim=args.vocab_size))
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/models.py", line 308, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 515, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 573, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/models.py", line 362, in call
    return self.model.call(x, mask)
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 2060, in call
    output_tensors, output_masks, output_shapes = self.run_internal_graph(inputs, masks)
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 2203, in run_internal_graph
    output_masks = to_list(layer.compute_mask(computed_tensor, computed_mask))
  File "/usr/lib/python2.7/site-packages/Keras-1.0.8-py2.7.egg/keras/engine/topology.py", line 608, in compute_mask
    'but was passed an input_mask: ' + str(input_mask))
Exception: Layer recurrentcontainer_input_1 does not support masking, but was passed an input_mask: Elemwise{neq,no_inplace}.0

**Comment by farizrahman4u** [comment]
Fixed.

**Comment by lvzhiqiang** [comment]
Sorry, I still encountered the same problem.

**Comment by farizrahman4u** [comment]
Oh.. had to fix in recurrentshop too. Now it works.

**Comment by manojpamk** [comment]
I still face the problem: (seq2seq and recurrentshop are updated)

model = Sequential()
model.add(Embedding(39,39, input_length=24, mask_zero=True))
model.add(SimpleSeq2Seq(input_length=24, input_dim=39, hidden_dim=10, output_length=22, output_dim=39))

Output:
```
`<ipython-input-73-0bdceeb6b04a> in <module>()
----> 1 model.add(SimpleSeq2Seq(input_length=24, input_dim=39, hidden_dim=10, output_length=22, output_dim=39))

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in add(self, layer)
    306                  output_shapes=[self.outputs[0]._keras_shape])
    307         else:
--> 308             output_tensor = layer(self.outputs[0])
    309             if type(output_tensor) is list:
    310                 raise Exception('All layers in a Sequential model '

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in __call__(self, x, mask)
    512         if inbound_layers:
    513             # this will call layer.build() if necessary
--> 514             self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
    515             input_added = True
    516 

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in add_inbound_node(self, inbound_layers, node_indices, tensor_indices)
    570         # creating the node automatically updates self.inbound_nodes
    571         # as well as outbound_nodes on inbound layers.
--> 572         Node.create_node(self, inbound_layers, node_indices, tensor_indices)
    573 
    574     def get_output_shape_for(self, input_shape):

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in create_node(cls, outbound_layer, inbound_layers, node_indices, tensor_indices)
    147 
    148         if len(input_tensors) == 1:
--> 149             output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
    150             output_masks = to_list(outbound_layer.compute_mask(input_tensors[0], input_masks[0]))
    151             # TODO: try to auto-infer shape if exception is raised by get_output_shape_for

/usr/local/lib/python2.7/dist-packages/keras/models.pyc in call(self, x, mask)
    360         if not self.built:
    361             self.build()
--> 362         return self.model.call(x, mask)
    363 
    364     def build(self, input_shape=None):

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in call(self, input, mask)
   2054             return self._output_tensor_cache[cache_key]
   2055         else:
-> 2056             output_tensors, output_masks, output_shapes = self.run_internal_graph(inputs, masks)
   2057             return output_tensors
   2058 

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in run_internal_graph(self, inputs, masks)
   2197                         computed_tensor, computed_mask = computed_data[0]
   2198                         output_tensors = to_list(layer.call(computed_tensor, computed_mask))
-> 2199                         output_masks = to_list(layer.compute_mask(computed_tensor, computed_mask))
   2200                         computed_tensors = [computed_tensor]
   2201                         computed_masks = [computed_mask]

/usr/local/lib/python2.7/dist-packages/keras/engine/topology.pyc in compute_mask(self, input, input_mask)
    605                 else:
    606                     raise Exception('Layer ' + self.name + ' does not support masking, ' +
--> 607                                     'but was passed an input_mask: ' + str(input_mask))
    608             # masking not explicitly supported: return None as mask
    609             return None
`
Exception: Layer recurrentcontainer_input_12 does not support masking, but was passed an input_mask: Elemwise{neq,no_inplace}.0
```

**Comment by Chinix** [comment]
if my inputs are word2vec vectors and thire length is variable, how can I solve the problem? @farizrahman4u

**Comment by ronanki** [comment]
Is it possible to have input_shape=(None, input_dimension) and output_shape=(None, output_dimension) -- so that we can provide variable length input and get desired length as output?

**Comment by amirveyseh** [comment]
is there any update on this issue?

I want to have a seq2seq model that could gets variable length input and gives variable length output (length of input and output are the same). I don't know how should I feed the training data to fit method and also get prediction. I've used this:

        model = Seq2Seq(input_dim=self.vocabulary_size, hidden_dim=10, output_dim=1)
        model.compile(loss='mse', optimizer='rmsprop')
        model.fit(seqs, targets, batch_size=_BATCH_SIZE, nb_epoch=_NEPOCH, validation_split=.2);

the seqs is of shape: (Number of sequences, Number of steps, Vocabulary Size) and the targets is of shape: (Number of sequences, Number of steps, 1); 

This code would produce this error: 

Traceback (most recent call last):
  File "", line 30, in train
    model = Seq2Seq(input_dim=self.vocabulary_size, hidden_dim=10, output_dim=1)
TypeError: Seq2Seq() takes at least 2 arguments (2 given)

**Comment by slashstar** [comment]
@amirveyseh, one way of doing what you want to do is pad your sequence and with zero vectors, and accordingly put <EOS> and <padding> tokens at the end of the corresponding output sequence. The idea is the network will try to learn padding too.
