### ISSUE TITLE
LSTMDecoderCell needs a get_config(self)

### ISSUE THREAD

**Issue by inzaghi250** [farizrahman4u/seq2seq#188]
I found that the latest commit removes the old get_config(self).

However in __init__:

    def __init__(self, hidden_dim=None, **kwargs):
        if hidden_dim:
            self.hidden_dim = hidden_dim
            kwargs['units'] = hidden_dim
        else:
            self.hidden_dim = kwargs['units']
        super(LSTMDecoderCell, self).__init__(**kwargs)

'units' is involved in the potential config. It may cause unfound key when we serialize and then deserialize LSTMDecoderCell.

**Comment by abhaikollara** [comment]
@inzaghi250 The `kwargs['units'] = hidden_dim` line was a bug, it has been removed in the latest commit

**Comment by inzaghi250** [comment]
@abhaikollara The remaining line
self.hidden_dim = kwargs['units']
still causes KeyError.
When LSTMDecoderCell is serialized, the get_config() of ExtendedRNNCell is used because LSTMDecoderCell does not have one.
This makes the 'units' attribute unincluded. 
When deserialized, __init__ is called with default hidden_dim (None), which excecutes the aforementioned line.

**Comment by abhaikollara** [comment]
@inzaghi250 Update seq2seq, your issue should be solved

**Comment by inzaghi250** [comment]
@abhaikollara I see the update:
12         if hidden_dim: 
13             self.hidden_dim = hidden_dim 
14         else: 
15             self.hidden_dim = self.output_dim 
16         super(LSTMDecoderCell, self).__init__(**kwargs) 

Should line 16 be above line 12? Otherwise, self.output_dim may get un-initialized before use.

**Comment by inzaghi250** [comment]
@abhaikollara I see the fix:
12         if hidden_dim: 
13             self.hidden_dim = hidden_dim 
14         else: 
15             self.hidden_dim = self.output_dim 
16         super(LSTMDecoderCell, self).__init__(**kwargs) 
However, self.output_dim still get uninitialized before use, because it is initialized at Line 16?

**Comment by inzaghi250** [comment]
@farizrahman4u Please help check the above issue. It causes simple save & load of models to fail.

**Comment by farizrahman4u** [comment]
@abhaikollara
